### ISSUE TITLE
Figure out why the plugin is initialized twice

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#34]
The plugin is initialized twice in my case, leading to [ugly hacks](https://github.com/IDArlingTeam/IDArling/blob/master/idarling/core/hooks.py#L682), we need to figured out why...
It can be noted that the plugin is initialized once if no IDB is loaded and twice if an IDB is loaded.

**Comment by NeatMonster** [comment]
On my Linux machine, `init()` and `term()` are only called once, whether or not I open a database.

**Comment by NeatMonster** [comment]
@patateqbool Could you remove your "ugly hacks" in your next commit and close this issue? Thanks!

**Comment by patateqbool** [comment]
No I can't because.... This is a bug ! Mouahahahahah \o>

**Comment by patateqbool** [comment]
The previous fix seems to crash IDA in some cases.
Here are the steps to reproduce in order to reach the bug:
- cp /bin/ls /tmp
- open /tmp/ls with ida and close to create /tmp/ls.i64
- cp /tmp/ls.i64 /tmp/ls2.i64
- ida64 /tmp/ls.i64 & ida64 /tmp/ls2.i64
Open first /tmp/ls2.i64 and then /tmp/ls.i64, the first one should open correctly and the second one should crash.
@NeatMonster can you check this out ? Thanks !

**Comment by NeatMonster** [comment]
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f4c9ba8d02e in py_call_nav_colorizer (nbytes=<optimized out>, ea=18446744073709551615, 
    col=<optimized out>) at obj/x64_linux_gcc_64_opt/wrappers/kernwin.cpp:5023
#2  _wrap_call_nav_colorizer (args=<optimized out>) at obj/x64_linux_gcc_64_opt/wrappers/kernwin.cpp:13904
#3  0x00007f4ca03a07e4 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#4  0x00007f4ca04cab88 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#5  0x00007f4ca039f580 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#6  0x00007f4ca04cab88 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#7  0x00007f4ca0480c59 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007f4ca03403c3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007f4ca049784c in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#10 0x00007f4ca03403c3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#11 0x00007f4ca0340531 in PyObject_CallFunction () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#12 0x00007f4c9ba5d8a9 in lambda_t::call_py_colorizer (ea=18446744073709551615, nbytes=0)
    at obj/x64_linux_gcc_64_opt/wrappers/kernwin.cpp:4978
#13 0x00005627bd35ad4d in ?? ()
#14 0x00005627bd35bd69 in ?? ()
#15 0x00007f4caa32ca24 in QT::QApplicationPrivate::notify_helper(QT::QObject*, QT::QEvent*) ()
   from /home/neat/ida-7.1/libQt5Widgets.so.5
#16 0x00007f4caa32c84f in QT::QApplication::notify(QT::QObject*, QT::QEvent*) ()
   from /home/neat/ida-7.1/libQt5Widgets.so.5
#17 0x00005627bd1a4509 in ?? ()
#18 0x00007f4ca95bd1e4 in QT::QCoreApplication::notifyInternal2(QT::QObject*, QT::QEvent*) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#19 0x00007f4ca95c127c in QT::QCoreApplication::sendEvent(QT::QObject*, QT::QEvent*) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#20 0x00007f4ca95be5c7 in QT::QCoreApplicationPrivate::sendPostedEvents(QT::QObject*, int, QT::QThreadData*) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#21 0x00007f4ca95bdf78 in QT::QCoreApplication::sendPostedEvents(QT::QObject*, int) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#22 0x00007f4ca96385e4 in ?? () from /home/neat/ida-7.1/libQt5Core.so.5
#23 0x00007f4ca762bfb7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f4ca762c1f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f4ca762c27c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f4ca9638e1d in QT::QEventDispatcherGlib::processEvents(QT::QFlags<QT::QEventLoop::ProcessEventsFlag>) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#27 0x00007f4ca433499c in ?? () from /home/neat/ida-7.1/plugins/platforms/../../libQt5XcbQpa.so.5
#28 0x00007f4ca95b9bce in QT::QEventLoop::processEvents(QT::QFlags<QT::QEventLoop::ProcessEventsFlag>) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#29 0x00007f4ca95b9eb9 in QT::QEventLoop::exec(QT::QFlags<QT::QEventLoop::ProcessEventsFlag>) ()
   from /home/neat/ida-7.1/libQt5Core.so.5
#30 0x00007f4ca95bd953 in QT::QCoreApplication::exec() () from /home/neat/ida-7.1/libQt5Core.so.5
#31 0x00007f4ca9af57a0 in QT::QGuiApplication::exec() () from /home/neat/ida-7.1/libQt5Gui.so.5
#32 0x00007f4caa32973f in QT::QApplication::exec() () from /home/neat/ida-7.1/libQt5Widgets.so.5
#33 0x00005627bd1a4261 in ?? ()
#34 0x00005627bd18b34a in ?? ()
#35 0x00007f4ca81781c1 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#36 0x00005627bd1907dd in ?? ()
#37 0x00007ffea27f5488 in ?? ()
#38 0x000000000000001c in ?? ()
#39 0x0000000000000002 in ?? ()
#40 0x00007ffea27f720a in ?? ()
#41 0x00007ffea27f7210 in ?? ()
#42 0x0000000000000000 in ?? ()
```

Sounds like it is related to the navbar colorizer. ;-)

**Comment by patateqbool** [comment]
Still not working on my side:
gef➤  bt
#0  0x0000000000000000 in  ()
#1  0x00007f8c39bdfe82 in sipSubClass_QApplication () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#2  0x00007f8c3aaafbd8 in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#3  0x00007f8c3aab3b2b in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#4  0x00007f8c39ba6f59 in convertFrom_QList_0101QWidget () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#5  0x00007f8c3aabb689 in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#6  0x00007f8c39a58f76 in meth_QApplication_topLevelWidgets () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#7  0x00007f8c4c8a43a9 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#8  0x00007f8c4c8a49d0 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#9  0x00007f8c4c8a49d0 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#10 0x00007f8c4c8a49d0 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#11 0x00007f8c4c8a49d0 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#12 0x00007f8c4c8ff0da in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#13 0x00007f8c4c890e0f in function_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#14 0x00007f8c4c8480e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#15 0x00007f8c4c8b449f in instancemethod_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#16 0x00007f8c4c8480e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#17 0x00007f8c4c8fe7d1 in PyEval_CallObjectWithKeywords () at /usr/lib/libpython2.7.so.1.0
#18 0x00007f8c4cc457a1 in  () at /home/patate/ida-7.1/plugins/python64.so
#19 0x00007f8c5664219b in  () at /home/patate/ida-7.1/libida64.so
#20 0x00007f8c56646669 in init_plugins () at /home/patate/ida-7.1/libida64.so
#21 0x000055f9cab0aedb in  ()
#22 0x000055f9cab0b95a in  ()
#23 0x000055f9cab0c3a3 in  ()
#24 0x000055f9caaf334a in  ()
#25 0x00007f8c53c8e06b in __libc_start_main () at /usr/lib/libc.so.6
#26 0x000055f9caaf87dd in  ()
#27 0x00007ffeb3429e18 in  ()
#28 0x000000000000001c in  ()
#29 0x0000000000000002 in  ()
#30 0x00007ffeb342a5f4 in  ()
#31 0x00007ffeb342a60f in  ()
#32 0x0000000000000000 in  ()

**Comment by NeatMonster** [comment]
@patateqbool Could you check again after commit https://github.com/IDArlingTeam/IDArling/commit/979bf7c30a4ab7652406383caec89d6bec923982?

**Comment by NyaMisty** [comment]
After `979bf7c` I can't even run the plugin hahah

**Comment by NeatMonster** [comment]
@NyaMisty Oops, should be fixed by @SilverBut 's commit (https://github.com/IDArlingTeam/IDArling/commit/d8a95b49d15ad10599150e074e22f1a5aae5bac1).

**Comment by patateqbool** [comment]
I'm currently at 4331e5dcdbfec785e7f484f0553c7fe64ceabd7d and I still have crashes :(
Here the backtrace
```#0  0x00007fd41ee76e7f in sipSubClass_QApplication () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#1  0x00007fd41f737bd8 in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#2  0x00007fd41f73bb2b in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#3  0x00007fd41ee3df59 in convertFrom_QList_0101QWidget () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#4  0x00007fd41f743689 in  () at /home/patate/ida-7.1/python/lib/python2.7/lib-dynload/sip.so
#5  0x00007fd41eceff76 in meth_QApplication_topLevelWidgets () at /home/patate/ida-7.1/python/PyQt5/QtWidgets.so
#6  0x00007fd431ab13a9 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#7  0x00007fd431ab19d0 in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#8  0x00007fd431b0c0da in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#9  0x00007fd431a9de0f in function_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#10 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#11 0x00007fd431ac149f in instancemethod_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#12 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#13 0x00007fd431af9de4 in slot_tp_init.lto_priv () at /usr/lib/libpython2.7.so.1.0
#14 0x00007fd431a732c5 in type_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#15 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#16 0x00007fd431ab680e in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#17 0x00007fd431b0c0da in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#18 0x00007fd431a9de0f in function_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#19 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#20 0x00007fd431ac149f in instancemethod_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#21 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#22 0x00007fd431af9de4 in slot_tp_init.lto_priv () at /usr/lib/libpython2.7.so.1.0
#23 0x00007fd431a732c5 in type_call.lto_priv () at /usr/lib/libpython2.7.so.1.0
#24 0x00007fd431a550e3 in PyObject_Call () at /usr/lib/libpython2.7.so.1.0
#25 0x00007fd431ab680e in PyEval_EvalFrameEx () at /usr/lib/libpython2.7.so.1.0
#26 0x00007fd431b0c0da in PyEval_EvalCodeEx () at /usr/lib/libpython2.7.so.1.0
#27 0x00007fd431e51a71 in  () at /home/patate/ida-7.1/plugins/python64.so
#28 0x00007fd43b84fb3a in  () at /home/patate/ida-7.1/libida64.so
#29 0x00007fd43b853669 in init_plugins () at /home/patate/ida-7.1/libida64.so
#30 0x0000562c04f22edb in  ()
#31 0x0000562c04f2395a in  ()
#32 0x0000562c04f243a3 in  ()
#33 0x0000562c04f0b34a in  ()
#34 0x00007fd438e9b06b in __libc_start_main () at /usr/lib/libc.so.6
#35 0x0000562c04f107dd in  ()
#36 0x00007ffc5837a218 in  ()
#37 0x000000000000001c in  ()
#38 0x0000000000000002 in  ()
#39 0x00007ffc5837b5f0 in  ()
#40 0x00007ffc5837b60b in  ()
#41 0x0000000000000000 in  ()
```

**Comment by NeatMonster** [comment]
@patateqbool What's the status on this issue? Still occurring?

**Comment by patateqbool** [comment]
Currently working on macOS. I'll tell you when I go back under my workflow which generates the problems.

**Comment by SilverBut** [comment]
I can partially reproduce it in latest commit 1d345cc3a608d86ffe93d1c871afa87f37923fa7, using IDA 7.1 Linux.

However I don't think the plugin is loaded twice, since if you do this patch in `idarling/inferface/plugin.py` you can see while the initialize message and `get me out` message print out 2 times, the message `already out` only output 1 time.

Maybe someone wrongly used `logging`?

![deepinscreenshot_select-area_20180828220913](https://user-images.githubusercontent.com/6560655/44728417-0c0f7980-ab0f-11e8-94fa-9f3c2af85a2c.png)


Patch: 
```
diff --git a/idarling/plugin.py b/idarling/plugin.py
index 648bb88..3ea62a1 100644
--- a/idarling/plugin.py
+++ b/idarling/plugin.py
@@ -147,6 +147,8 @@ class Plugin(ida_idaapi.plugin_t):
         """
         Print the banner into the console.
         """
+        logger.info("GET ME OUT!")
+        print("Already out.")
         copyright = "(c) %s" % self.PLUGIN_AUTHORS
 
         logger.info("-" * 75)
```

**Comment by SilverBut** [comment]
Alright I see...

**Comment by SilverBut** [comment]
@patateqbool 

By the way, this comment

> In addition, the latest commit introduced these messages when closing IDA
> 
> QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout

Has now been resolved (but not comitted yet).

**Comment by patateqbool** [comment]
@SilverBut ack, thank you.

**Comment by NeatMonster** [comment]
@SilverBut I believed it is fixed in the master branch.

The layout of the network settings tab was being added to `self` instead of `tab`.

**Comment by SilverBut** [comment]
> @SilverBut I believed it is fixed in the master branch.

@NeatMonster At least not in commit 1d345cc3a608d86ffe93d1c871afa87f37923fa7 for IDA 7.1 under Linux. You can still see those hints when opening the "settings" dialog.

**Comment by NeatMonster** [comment]
> QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout

@patateqbool Could you check if the message is gone after the recent changes? Have you encountered another crash of IDA since to `QCoreApplication` to `qApp` change?

**Comment by patateqbool** [comment]
@NeatMonster nop, it's fine now. I don't have crash anymore too. :) I think we can close this issue.
